### ISSUE TITLE
Produksjonsbilder skaleres uproporsjonalt i detaljvising

### ISSUE THREAD

**Issue by jakobsen** [Studentersamfundets-Interne-Teater/sit-web#18]
Her er bildet skalert korrekt:

![bilde](https://user-images.githubusercontent.com/16143117/95022213-14cfc380-0676-11eb-814d-db101c1c4913.png)

Når jeg gjør siden smalere skjer dette:

![bilde](https://user-images.githubusercontent.com/16143117/95022235-303ace80-0676-11eb-99ac-70b4a1dbd3a5.png)

De aktuelle CSS-selectorene er `.production-banner` og `.production-banner img`.

**Comment by jakobsen** [comment]
Må komme tilbake til denne etterhvert som vi får siden ut, men en fiks med CSS er å bruke `object-fit: cover`.

**Comment by livejac** [comment]
Er adressert i PR #23 :)
