### ISSUE TITLE
Horisontal skroll

### ISSUE THREAD

**Issue by jakobsen** [Studentersamfundets-Interne-Teater/sit-web#22]
Siden skroller horisontalt. Dette gjelder på alle sider, så synderen er mest sannsynlig `.topnav`, `<content>` eller `.footer`.

**Comment by livejac** [comment]
Jeg klarer ikke gjenskape feilen hverken i Chrome eller Safari. Hva slags nettleser bruker du?

**Comment by jakobsen** [comment]
Rart – hos meg skjer det i både Firefox, Chrome og Safari:

**Chorme**
![chrome](https://user-images.githubusercontent.com/16143117/95773447-c8f8cc00-0cbe-11eb-9c71-84b77f7c6e38.png)

**Safari**
<img width="1253" alt="safari" src="https://user-images.githubusercontent.com/16143117/95773457-cb5b2600-0cbe-11eb-8931-b9cdc74a927d.png">

**Firefox**
<img width="1177" alt="firefox" src="https://user-images.githubusercontent.com/16143117/95773462-cd24e980-0cbe-11eb-91cb-e6e9fcc0a6b2.png">

**Comment by jakobsen** [comment]
Dette løste seg selv 🤷
